export const writings = [
  {
    slug: 'legacy',
    title: 'Legacy',
    paragraphs: [
      'I think this is one concept I’ve been thinking about wrongly for most of my life.',
      'I’ve been living for 25 years, and out of those 25, let’s say 15 are the ones that really defined my life, my aspirations, my mental model of the world, and more.',
      'For some reason, early in my life, I started noticing something interesting. I used to be really into history, and I had this realization: history only talks about the people who made a dent. Kings, queens, scientists, famous writers… the names that “won.”',
      'But what about the sweet lady selling potatoes on the side of the road, with 2–3 kids, and a husband who’s a soldier that everyone in the city knows because he helps people and defends them against tyranny?',
      'I used to ask myself:',
      'Why do we only learn about the people who got to “win”? What about the people who helped?',
      'But more importantly, if I’m being honest, I think there was something selfish in me. I hated the idea of being forgotten. It made me sick.',
      'We all live, love, laugh, cry, try our best… just to be forgotten? Why?',
      'That thought shaped me more than I realized. It fed my ambition. I wanted to do things that would make me remembered, not just my work, but me. And that was how I thought for a long time.',
      'Then I started working with Liam, someone I respect and love, and he saw life completely differently.',
      'Liam is interesting, and here’s why.',
      'The first time I met him in person at Cornell, we went to see this river. From a distance, I said, “Oh, it probably looks better if we go closer,” not realizing Liam was wearing the wrong shoes for that kind of adventure.',
      'We moved closer. Liam slipped. His phone fell into the river, and the current was so strong there was no way we were getting it back.',
      'I expected him to be mad. Or at least upset.',
      'But he was laughing.',
      'I remember thinking, this guy is pretending. Because if that were me, I would’ve been sick.',
      'So I asked him about it.',
      'And he just said, “It’s just a phone, bro.”',
      'To me, that wasn’t “just a phone.” My phone is my life, my everything haha.',
      'But that moment stuck with me. Liam was genuinely selfless—through and through.',
      'Later, we talked about legacy. I asked him what he thought about it.',
      'He said he didn’t care.',
      'I couldn’t understand that.',
      'How can you not care? How?',
      'Here’s someone who’s really good at what they do, and they’re saying they don’t care about legacy. If it were me, I’d want people to remember me.',
      'But for Liam, it wasn’t about “me.” It was about his outputs, his work.',
      'He would say this all the time:',
      '“No one cares, bro.”',
      'And I couldn’t understand that for a long time.',
      'That desire to be remembered as a person had even spilled into how I thought about work. Everything was about me.',
      'Then I heard Kanye say something on a podcast:',
      '“The point of legacy is to be forgotten.”',
      'And I was like… what?',
      'Here’s someone with a god-level ego saying they want to be forgotten?',
      'But the more I listened, the more I understood what he meant.',
      'He was saying: my work will be the legacy.',
      'He said something like:',
      '“Who designed the sidewalks? The electric poles? The gutters?”',
      'And that hit me.',
      'Imagine serving society so well that your work becomes the legacy. That tells a better story than the person behind it ever could.',
      'Because the person, the character, has flaws.',
      'But the work?',
      'The work speaks for itself.',
      'And when people see it, they only say one thing:',
      '“This human cared.”',
      'That hit me.',
      'Now I understand.',
    ],
  },
];
